# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account/credentials.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61\x63\x63ount/credentials.proto\x12\x13\x61\x63\x63ount.credentials\x1a\x0c\x63ommon.proto\"0\n\rVerifyRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1b\n\rVerifySuccess\x12\n\n\x02id\x18\x01 \x01(\t\"\xbc\x01\n\x0eVerifyResponse\x12\x35\n\x07success\x18\x01 \x01(\x0b\x32\".account.credentials.VerifySuccessH\x00\x12>\n\x13invalid_credentials\x18\x02 \x01(\x0b\x32\x1f.common.InvalidCredentialsErrorH\x00\x12)\n\x08internal\x18\x03 \x01(\x0b\x32\x15.common.InternalErrorH\x00\x42\x08\n\x06result\"O\n\x15UpdatePasswordRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cold_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\"\x17\n\x15UpdatePasswordSuccess\"\xfb\x01\n\x16UpdatePasswordResponse\x12=\n\x07success\x18\x01 \x01(\x0b\x32*.account.credentials.UpdatePasswordSuccessH\x00\x12\x38\n\x10invalid_password\x18\x02 \x01(\x0b\x32\x1c.common.InvalidPasswordErrorH\x00\x12\x33\n\x0euser_not_found\x18\x03 \x01(\x0b\x32\x19.common.UserNotFoundErrorH\x00\x12)\n\x08internal\x18\x04 \x01(\x0b\x32\x15.common.InternalErrorH\x00\x42\x08\n\x06resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account.credentials_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFYREQUEST']._serialized_start=64
  _globals['_VERIFYREQUEST']._serialized_end=112
  _globals['_VERIFYSUCCESS']._serialized_start=114
  _globals['_VERIFYSUCCESS']._serialized_end=141
  _globals['_VERIFYRESPONSE']._serialized_start=144
  _globals['_VERIFYRESPONSE']._serialized_end=332
  _globals['_UPDATEPASSWORDREQUEST']._serialized_start=334
  _globals['_UPDATEPASSWORDREQUEST']._serialized_end=413
  _globals['_UPDATEPASSWORDSUCCESS']._serialized_start=415
  _globals['_UPDATEPASSWORDSUCCESS']._serialized_end=438
  _globals['_UPDATEPASSWORDRESPONSE']._serialized_start=441
  _globals['_UPDATEPASSWORDRESPONSE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
