# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account/permissions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61\x63\x63ount/permissions.proto\x12\x13\x61\x63\x63ount.permissions\x1a\x0c\x63ommon.proto\"$\n\x16PermissionsByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x16PermissionsByIdSuccess\x12\r\n\x05roles\x18\x01 \x03(\t\x12\x13\n\x0bpermissions\x18\x02 \x03(\t\"\xc3\x01\n\x17PermissionsByIdResponse\x12>\n\x07success\x18\x01 \x01(\x0b\x32+.account.permissions.PermissionsByIdSuccessH\x00\x12\x33\n\x0euser_not_found\x18\x02 \x01(\x0b\x32\x19.common.UserNotFoundErrorH\x00\x12)\n\x08internal\x18\x03 \x01(\x0b\x32\x15.common.InternalErrorH\x00\x42\x08\n\x06resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account.permissions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERMISSIONSBYIDREQUEST']._serialized_start=64
  _globals['_PERMISSIONSBYIDREQUEST']._serialized_end=100
  _globals['_PERMISSIONSBYIDSUCCESS']._serialized_start=102
  _globals['_PERMISSIONSBYIDSUCCESS']._serialized_end=162
  _globals['_PERMISSIONSBYIDRESPONSE']._serialized_start=165
  _globals['_PERMISSIONSBYIDRESPONSE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
