# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\" \n\rInternalError\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x11UserNotFoundError\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x17InvalidCredentialsError\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x1b\x45mailAlreadyRegisteredError\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14InvalidPasswordError\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTERNALERROR']._serialized_start=24
  _globals['_INTERNALERROR']._serialized_end=56
  _globals['_USERNOTFOUNDERROR']._serialized_start=58
  _globals['_USERNOTFOUNDERROR']._serialized_end=94
  _globals['_INVALIDCREDENTIALSERROR']._serialized_start=96
  _globals['_INVALIDCREDENTIALSERROR']._serialized_end=138
  _globals['_EMAILALREADYREGISTEREDERROR']._serialized_start=140
  _globals['_EMAILALREADYREGISTEREDERROR']._serialized_end=186
  _globals['_INVALIDPASSWORDERROR']._serialized_start=188
  _globals['_INVALIDPASSWORDERROR']._serialized_end=227
# @@protoc_insertion_point(module_scope)
