apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-worker
  namespace: charisma
  labels:
    app: ml-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-worker
  template:
    metadata:
      labels:
        app: ml-worker
    spec:
      serviceAccountName: charisma-migrator-waiter
      initContainers:
        - name: wait-for-migrator
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - kubectl
            - wait
            - --for=condition=complete
            - --timeout=600s
            - job/migrator
      containers:
        - name: ml-worker
          image: ghcr.io/desmitry/charisma-master-ml-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - app.celery_app
            - worker
            - --loglevel=info
            - --pool=solo
          envFrom:
            - configMapRef:
                name: charisma-config
            - secretRef:
                name: charisma-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
