apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: charisma
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
