apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-worker
  namespace: charisma
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ml-worker
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
