---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  namespace: charisma
  labels:
    app: seaweedfs-master
spec:
  type: ClusterIP
  selector:
    app: seaweedfs-master
  ports:
    - port: 9333
      targetPort: 9333
      name: master
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
  namespace: charisma
  labels:
    app: seaweedfs-volume
spec:
  type: ClusterIP
  selector:
    app: seaweedfs-volume
  ports:
    - port: 8080
      targetPort: 8080
      name: volume
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
  namespace: charisma
  labels:
    app: seaweedfs-filer
spec:
  type: ClusterIP
  selector:
    app: seaweedfs-filer
  ports:
    - port: 8888
      targetPort: 8888
      name: filer
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3
  namespace: charisma
  labels:
    app: seaweedfs-s3
spec:
  type: ClusterIP
  selector:
    app: seaweedfs-s3
  ports:
    - port: 8333
      targetPort: 8333
      name: s3
