import { AnalysisResult } from "@/types/analysis";

export const mockAnalysis: AnalysisResult = {
  task_id: "550e8400-e29b-41d4-a716-446655440000",
  video_path:
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  transcript: [
    {
      start: 0.0,
      end: 8.5,
      text: "Сегодня мы представляем три революционных продукта. Первый — это широкоэкранный iPod с сенсорным управлением. Второй — это революционный мобильный телефон. И третий — это прорывное устройство для интернет-коммуникаций.",
      words: [
        { start: 0.0, end: 0.6, text: "Сегодня", is_filler: false },
        { start: 0.7, end: 1.0, text: "мы", is_filler: false },
        { start: 1.1, end: 1.7, text: "представляем", is_filler: false },
        { start: 1.8, end: 2.1, text: "три", is_filler: false },
        { start: 2.2, end: 2.9, text: "революционных", is_filler: false },
        { start: 3.0, end: 3.5, text: "продукта", is_filler: false },
        { start: 3.7, end: 4.0, text: "Первый", is_filler: false },
        { start: 4.2, end: 4.4, text: "это", is_filler: false },
        { start: 4.5, end: 5.2, text: "широкоэкранный", is_filler: false },
        { start: 5.3, end: 5.7, text: "iPod", is_filler: false },
        { start: 5.8, end: 6.0, text: "с", is_filler: false },
        { start: 6.1, end: 6.7, text: "сенсорным", is_filler: false },
        { start: 6.8, end: 7.4, text: "управлением", is_filler: false },
        { start: 7.6, end: 8.0, text: "Второй", is_filler: false },
        { start: 8.1, end: 8.5, text: "это", is_filler: false },
      ],
    },
    {
      start: 8.6,
      end: 15.2,
      text: "Это революционный мобильный телефон. И третий — это прорывное устройство для интернет-коммуникаций.",
      words: [
        { start: 8.6, end: 9.0, text: "Это", is_filler: false },
        { start: 9.1, end: 9.7, text: "революционный", is_filler: false },
        { start: 9.8, end: 10.3, text: "мобильный", is_filler: false },
        { start: 10.4, end: 10.9, text: "телефон", is_filler: false },
        { start: 11.1, end: 11.3, text: "И", is_filler: false },
        { start: 11.4, end: 11.8, text: "третий", is_filler: false },
        { start: 12.0, end: 12.3, text: "это", is_filler: false },
        { start: 12.4, end: 13.1, text: "прорывное", is_filler: false },
        { start: 13.2, end: 13.7, text: "устройство", is_filler: false },
        { start: 13.8, end: 14.1, text: "для", is_filler: false },
        { start: 14.2, end: 14.7, text: "интернет", is_filler: false },
        { start: 14.8, end: 15.2, text: "коммуникаций", is_filler: false },
      ],
    },
    {
      start: 15.3,
      end: 22.8,
      text: "Итак, три вещи: широкоэкранный iPod с сенсорным управлением, революционный мобильный телефон и прорывное устройство для интернет-коммуникаций.",
      words: [
        { start: 15.3, end: 15.6, text: "Итак", is_filler: false },
        { start: 15.8, end: 16.0, text: "три", is_filler: false },
        { start: 16.1, end: 16.5, text: "вещи", is_filler: false },
        { start: 16.7, end: 17.4, text: "широкоэкранный", is_filler: false },
        { start: 17.5, end: 17.9, text: "iPod", is_filler: false },
        { start: 18.0, end: 18.2, text: "с", is_filler: false },
        { start: 18.3, end: 18.9, text: "сенсорным", is_filler: false },
        { start: 19.0, end: 19.6, text: "управлением", is_filler: false },
        { start: 19.8, end: 20.4, text: "революционный", is_filler: false },
        { start: 20.5, end: 21.0, text: "мобильный", is_filler: false },
        { start: 21.1, end: 21.6, text: "телефон", is_filler: false },
        { start: 21.8, end: 22.0, text: "и", is_filler: false },
        { start: 22.1, end: 22.8, text: "прорывное", is_filler: false },
      ],
    },
    {
      start: 22.9,
      end: 30.5,
      text: "iPod, телефон и интернет-коммуникатор. iPod, телефон... понимаете? Это не три отдельных устройства.",
      words: [
        { start: 22.9, end: 23.3, text: "iPod", is_filler: false },
        { start: 23.5, end: 23.8, text: "телефон", is_filler: false },
        { start: 24.0, end: 24.2, text: "и", is_filler: false },
        { start: 24.3, end: 24.9, text: "интернет", is_filler: false },
        { start: 25.0, end: 25.6, text: "коммуникатор", is_filler: false },
        { start: 25.8, end: 26.2, text: "iPod", is_filler: false },
        { start: 26.4, end: 26.7, text: "телефон", is_filler: false },
        { start: 27.0, end: 27.6, text: "понимаете", is_filler: false },
        { start: 27.8, end: 28.1, text: "Это", is_filler: false },
        { start: 28.2, end: 28.4, text: "не", is_filler: false },
        { start: 28.5, end: 28.7, text: "три", is_filler: false },
        { start: 28.8, end: 29.4, text: "отдельных", is_filler: false },
        { start: 29.5, end: 30.5, text: "устройства", is_filler: false },
      ],
    },
    {
      start: 30.6,
      end: 38.2,
      text: "Это одно устройство, и мы называем его iPhone. Сегодня Apple изобретает телефон заново.",
      words: [
        { start: 30.6, end: 30.9, text: "Это", is_filler: false },
        { start: 31.0, end: 31.3, text: "одно", is_filler: false },
        { start: 31.4, end: 32.0, text: "устройство", is_filler: false },
        { start: 32.2, end: 32.4, text: "и", is_filler: false },
        { start: 32.5, end: 32.7, text: "мы", is_filler: false },
        { start: 32.8, end: 33.3, text: "называем", is_filler: false },
        { start: 33.4, end: 33.7, text: "его", is_filler: false },
        { start: 33.8, end: 34.2, text: "iPhone", is_filler: false },
        { start: 34.4, end: 34.9, text: "Сегодня", is_filler: false },
        { start: 35.0, end: 35.4, text: "Apple", is_filler: false },
        { start: 35.5, end: 36.2, text: "изобретает", is_filler: false },
        { start: 36.3, end: 36.8, text: "телефон", is_filler: false },
        { start: 36.9, end: 37.4, text: "заново", is_filler: false },
      ],
    },
    {
      start: 38.3,
      end: 46.8,
      text: "Ну, эм, хорошо, давайте поговорим о том, что делает iPhone таким особенным. У него самый большой и яркий экран, который мы когда-либо создавали.",
      words: [
        { start: 38.3, end: 38.6, text: "Ну", is_filler: true },
        { start: 38.8, end: 39.1, text: "эм", is_filler: true },
        { start: 39.3, end: 39.7, text: "хорошо", is_filler: false },
        { start: 39.9, end: 40.3, text: "давайте", is_filler: false },
        { start: 40.4, end: 40.9, text: "поговорим", is_filler: false },
        { start: 41.0, end: 41.2, text: "о", is_filler: false },
        { start: 41.3, end: 41.6, text: "том", is_filler: false },
        { start: 41.8, end: 42.1, text: "что", is_filler: false },
        { start: 42.2, end: 42.7, text: "делает", is_filler: false },
        { start: 42.8, end: 43.2, text: "iPhone", is_filler: false },
        { start: 43.3, end: 43.7, text: "таким", is_filler: false },
        { start: 43.8, end: 44.4, text: "особенным", is_filler: false },
        { start: 44.6, end: 44.8, text: "У", is_filler: false },
        { start: 44.9, end: 45.2, text: "него", is_filler: false },
        { start: 45.3, end: 45.7, text: "самый", is_filler: false },
        { start: 45.8, end: 46.2, text: "большой", is_filler: false },
        { start: 46.3, end: 46.8, text: "и", is_filler: false },
      ],
    },
    {
      start: 46.9,
      end: 54.3,
      text: "У него самый большой и яркий экран, который мы когда-либо создавали. И самое главное — это сенсорное управление.",
      words: [
        { start: 46.9, end: 47.2, text: "яркий", is_filler: false },
        { start: 47.3, end: 47.7, text: "экран", is_filler: false },
        { start: 47.8, end: 48.2, text: "который", is_filler: false },
        { start: 48.3, end: 48.6, text: "мы", is_filler: false },
        { start: 48.7, end: 49.2, text: "когда", is_filler: false },
        { start: 49.3, end: 49.6, text: "либо", is_filler: false },
        { start: 49.7, end: 50.2, text: "создавали", is_filler: false },
        { start: 50.4, end: 50.6, text: "И", is_filler: false },
        { start: 50.7, end: 50.9, text: "самое", is_filler: false },
        { start: 51.0, end: 51.4, text: "главное", is_filler: false },
        { start: 51.6, end: 51.8, text: "это", is_filler: false },
        { start: 51.9, end: 52.5, text: "сенсорное", is_filler: false },
        { start: 52.6, end: 54.3, text: "управление", is_filler: false },
      ],
    },
    {
      start: 54.4,
      end: 62.1,
      text: "Мы изобрели новую технологию под названием мультитач. Это работает как магия. У вас больше нет необходимости в стилусе.",
      words: [
        { start: 54.4, end: 54.6, text: "Мы", is_filler: false },
        { start: 54.7, end: 55.3, text: "изобрели", is_filler: false },
        { start: 55.4, end: 55.8, text: "новую", is_filler: false },
        { start: 55.9, end: 56.5, text: "технологию", is_filler: false },
        { start: 56.6, end: 56.9, text: "под", is_filler: false },
        { start: 57.0, end: 57.5, text: "названием", is_filler: false },
        { start: 57.6, end: 58.2, text: "мультитач", is_filler: false },
        { start: 58.4, end: 58.7, text: "Это", is_filler: false },
        { start: 58.8, end: 59.3, text: "работает", is_filler: false },
        { start: 59.4, end: 59.7, text: "как", is_filler: false },
        { start: 59.8, end: 60.3, text: "магия", is_filler: false },
        { start: 60.5, end: 60.7, text: "У", is_filler: false },
        { start: 60.8, end: 61.1, text: "вас", is_filler: false },
        { start: 61.2, end: 61.6, text: "больше", is_filler: false },
        { start: 61.7, end: 62.1, text: "нет", is_filler: false },
      ],
    },
    {
      start: 62.2,
      end: 70.5,
      text: "У вас больше нет необходимости в стилусе. Это невероятно точное управление пальцами. И это намного лучше, чем любое сенсорное управление, которое когда-либо было изобретено.",
      words: [
        { start: 62.2, end: 62.5, text: "необходимости", is_filler: false },
        { start: 62.6, end: 62.8, text: "в", is_filler: false },
        { start: 62.9, end: 63.4, text: "стилусе", is_filler: false },
        { start: 63.6, end: 63.9, text: "Это", is_filler: false },
        { start: 64.0, end: 64.6, text: "невероятно", is_filler: false },
        { start: 64.7, end: 65.2, text: "точное", is_filler: false },
        { start: 65.3, end: 65.8, text: "управление", is_filler: false },
        { start: 65.9, end: 66.4, text: "пальцами", is_filler: false },
        { start: 66.6, end: 66.8, text: "И", is_filler: false },
        { start: 66.9, end: 67.2, text: "это", is_filler: false },
        { start: 67.3, end: 67.7, text: "намного", is_filler: false },
        { start: 67.8, end: 68.2, text: "лучше", is_filler: false },
        { start: 68.4, end: 68.7, text: "чем", is_filler: false },
        { start: 68.8, end: 69.2, text: "любое", is_filler: false },
        { start: 69.3, end: 70.0, text: "сенсорное", is_filler: false },
        { start: 70.1, end: 70.5, text: "управление", is_filler: false },
      ],
    },
    {
      start: 70.6,
      end: 78.9,
      text: "Короче говоря, iPhone — это смартфон, iPod и интернет-коммуникатор в одном устройстве. И мы думаем, что это изменит всё.",
      words: [
        { start: 70.6, end: 71.1, text: "Короче", is_filler: true },
        { start: 71.2, end: 71.7, text: "говоря", is_filler: true },
        { start: 71.9, end: 72.3, text: "iPhone", is_filler: false },
        { start: 72.5, end: 72.8, text: "это", is_filler: false },
        { start: 72.9, end: 73.5, text: "смартфон", is_filler: false },
        { start: 73.7, end: 73.9, text: "iPod", is_filler: false },
        { start: 74.1, end: 74.3, text: "и", is_filler: false },
        { start: 74.4, end: 75.0, text: "интернет", is_filler: false },
        { start: 75.1, end: 75.7, text: "коммуникатор", is_filler: false },
        { start: 75.8, end: 76.0, text: "в", is_filler: false },
        { start: 76.1, end: 76.4, text: "одном", is_filler: false },
        { start: 76.5, end: 77.1, text: "устройстве", is_filler: false },
        { start: 77.3, end: 77.5, text: "И", is_filler: false },
        { start: 77.6, end: 77.8, text: "мы", is_filler: false },
        { start: 77.9, end: 78.3, text: "думаем", is_filler: false },
        { start: 78.4, end: 78.6, text: "что", is_filler: false },
        { start: 78.7, end: 78.9, text: "это", is_filler: false },
      ],
    },
    {
      start: 79.0,
      end: 87.2,
      text: "И мы думаем, что это изменит всё. Спасибо вам большое. Мы очень рады представить вам iPhone сегодня.",
      words: [
        { start: 79.0, end: 79.3, text: "изменит", is_filler: false },
        { start: 79.4, end: 79.7, text: "всё", is_filler: false },
        { start: 79.9, end: 80.4, text: "Спасибо", is_filler: false },
        { start: 80.5, end: 80.8, text: "вам", is_filler: false },
        { start: 80.9, end: 81.3, text: "большое", is_filler: false },
        { start: 81.5, end: 81.7, text: "Мы", is_filler: false },
        { start: 81.8, end: 82.2, text: "очень", is_filler: false },
        { start: 82.3, end: 82.7, text: "рады", is_filler: false },
        { start: 82.8, end: 83.4, text: "представить", is_filler: false },
        { start: 83.5, end: 83.8, text: "вам", is_filler: false },
        { start: 83.9, end: 84.3, text: "iPhone", is_filler: false },
        { start: 84.4, end: 84.9, text: "сегодня", is_filler: false },
      ],
    },
  ],
  tempo: [
    { time: 0.0, wpm: 145.2, zone: "green" },
    { time: 10.0, wpm: 152.8, zone: "green" },
    { time: 20.0, wpm: 148.3, zone: "green" },
    { time: 30.0, wpm: 141.7, zone: "green" },
    { time: 40.0, wpm: 156.4, zone: "green" },
    { time: 50.0, wpm: 149.1, zone: "green" },
    { time: 60.0, wpm: 143.6, zone: "green" },
    { time: 70.0, wpm: 138.9, zone: "yellow" },
    { time: 80.0, wpm: 147.2, zone: "green" },
    { time: 87.2, wpm: 144.5, zone: "green" },
  ],
  fillers_summary: {
    count: 4,
    ratio: 0.028,
  },
  confidence_index: {
    total: 88.7,
    components: {
      volume_score: 91.2,
      filler_score: 85.3,
      gaze_score: 89.6,
    },
  },
  summary:
    "Спикер представил революционный продукт iPhone, объединяющий три устройства в одном: широкоэкранный iPod с сенсорным управлением, революционный мобильный телефон и прорывное устройство для интернет-коммуникаций. Ключевая особенность — технология мультитач, которая позволяет управлять устройством пальцами без стилуса. Выступление эмоциональное, структурированное, с минимальным использованием слов-паразитов. Темп речи оптимальный на протяжении всего выступления.",
  structure:
    "Вступление эффектное с драматической презентацией трех продуктов, которые оказываются одним устройством. Основная часть последовательно раскрывает ключевые особенности iPhone: большой яркий экран, сенсорное управление, технология мультитач. Заключение краткое и эмоциональное. Структура соответствует классической презентации продукта с элементами драматизма.",
  mistakes:
    "Обнаружено 4 слова-паразита: 'ну' (1 раз), 'эм' (1 раз), 'короче говоря' (1 раз). Темп речи немного замедлился в период 70-75 секунд (138.9 WPM), но оставался в допустимом диапазоне. В целом выступление очень качественное с минимальными недостатками.",
  ideal_text:
    "Сегодня мы представляем три революционных продукта. Первый — это широкоэкранный iPod с сенсорным управлением. Второй — это революционный мобильный телефон. И третий — это прорывное устройство для интернет-коммуникаций. Итак, три вещи: широкоэкранный iPod с сенсорным управлением, революционный мобильный телефон и прорывное устройство для интернет-коммуникаций. iPod, телефон и интернет-коммуникатор. iPod, телефон... понимаете? Это не три отдельных устройства. Это одно устройство, и мы называем его iPhone. Сегодня Apple изобретает телефон заново. Хорошо, давайте поговорим о том, что делает iPhone таким особенным. У него самый большой и яркий экран, который мы когда-либо создавали. И самое главное — это сенсорное управление. Мы изобрели новую технологию под названием мультитач. Это работает как магия. У вас больше нет необходимости в стилусе. Это невероятно точное управление пальцами. И это намного лучше, чем любое сенсорное управление, которое когда-либо было изобретено. iPhone — это смартфон, iPod и интернет-коммуникатор в одном устройстве. И мы думаем, что это изменит всё. Спасибо вам большое. Мы очень рады представить вам iPhone сегодня.",
  persona_feedback:
    "Как Стив Джобс, я бы сказал: 'Отличная работа! Ты использовал драматический прием с тремя продуктами, которые оказались одним — это классика. Эмоция есть, видение есть, страсть чувствуется. Единственное — можно было добавить больше пауз для драматического эффекта в ключевых моментах. Но в целом — это то, как нужно представлять продукт, который меняет индустрию.'",
  slide_text_density: 32.4,
};

