apiVersion: v1
kind: ConfigMap
metadata:
  name: charisma-config
  namespace: charisma
data:
  MODE: "prod"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  SEAWEEDFS_ENDPOINT: "http://seaweedfs-s3:8333"
  ORIGIN_URL: "https://charisma.example.com"
  GIGACHAT_SCOPE: "GIGACHAT_API_PERS"
  GIGACHAT_MODEL_NAME: "GigaChat"
  SBER_SPEECH_SCOPE: "SALUTE_SPEECH_B2B"
  OPENAI_API_BASE: "https://api.openai.com/v1"
  OPENAI_MODEL_NAME: "gpt-4"
  WHISPER_MODEL_NAME: "whisper-1"
  WHISPER_MODEL_TYPE: "base"
  WHISPER_DEVICE: "cpu"
  WHISPER_COMPUTE_TYPE: "int8"
