apiVersion: v1
kind: Secret
metadata:
  name: charisma-secrets
  namespace: charisma
type: Opaque
stringData:
  OPENAI_API_KEY: "CHANGE_ME"
  GIGACHAT_CREDENTIALS: "CHANGE_ME"
  SBER_SALUTE_CREDENTIALS: "CHANGE_ME"
  ORIGIN_URL: "https://charisma.geekiot.tech"
  POSTGRES_USER: "charisma"
  POSTGRES_PASSWORD: "charisma"
  POSTGRES_DB: "charisma"
